---
collections:
  - name: community.proxmox
  - name: ansible.windows
  - name: microsoft.ad 
  - name: community.general 

roles:
  - name: pvwa
    src: https://github.com/cyberark/pvwa.git
    scm: git
  - name: cpm
    src: https://github.com/cyberark/cpm.git
    scm: git
  - name: psm
    src: https://github.com/cyberark/psm.git
    scm: git
