all:
  children:
    windows:
      vars:
        # template_id removed from here
        ostype: win10
        ci_user: "Administrator"
      children:
        domain_controllers:
          hosts:
            dc-01: { vmid: 300, ip: "10.0.3.1",  mac: "BC:24:11:00:DC:01", target_node: "proxmox02", template_id: 9002 }
            dc-02: { vmid: 301, ip: "10.0.3.2",  mac: "BC:24:11:00:DC:02", target_node: "proxmox03", template_id: 9003 }
        cyberark_components:
          children:
            vault:
              hosts:
                vault-01: { vmid: 302, ip: "10.0.3.3", mac: "BC:24:11:F1:7B:BC", target_node: "proxmox02", template_id: 9002 }
                vault-02: { vmid: 303, ip: "10.0.3.4", mac: "BC:24:11:0D:C0:79", target_node: "proxmox03", template_id: 9003 }
            pvwa:
              hosts:
                pvwa-01: { vmid: 304, ip: "10.0.3.5", mac: "BC:24:11:2D:A1:BE", target_node: "proxmox02", template_id: 9002 }
                pvwa-02: { vmid: 305, ip: "10.0.3.6", mac: "BC:24:11:90:D4:37", target_node: "proxmox03", template_id: 9003 }
            cpm:
              hosts:
                cpm-01: { vmid: 306, ip: "10.0.3.7", mac: "BC:24:11:C2:FE:FA", target_node: "proxmox02", template_id: 9002 }
                cpm-02: { vmid: 307, ip: "10.0.3.8", mac: "BC:24:11:F7:30:6B", target_node: "proxmox03", template_id: 9003 }
            psm:
              hosts:
                psm-01: { vmid: 308, ip: "10.0.3.9", mac: "BC:24:11:96:4E:C8", target_node: "proxmox02", template_id: 9002 }
                psm-02: { vmid: 309, ip: "10.0.3.10", mac: "BC:24:11:A7:E8:13", target_node: "proxmox03", template_id: 9003 }

    linux:
      vars:
        # template_id removed from here
        ostype: l26
        ci_user: "mgmt"
      hosts:
        htmlgw-01: { vmid: 310, ip: "10.0.3.11", mac: "BC:24:11:60:F1:D8", target_node: "proxmox02", template_id: 9102 }
        htmlgw-02: { vmid: 311, ip: "10.0.3.12", mac: "BC:24:11:1D:19:9E", target_node: "proxmox03", template_id: 9103 }
        psmp-01:   { vmid: 312, ip: "10.0.3.13", mac: "BC:24:11:7C:97:23", target_node: "proxmox02", template_id: 9102 }
        psmp-02:   { vmid: 313, ip: "10.0.3.14", mac: "BC:24:11:76:93:23", target_node: "proxmox03", template_id: 9103 }
        lb-01:     { vmid: 314, ip: "10.0.3.15", mac: "BC:24:11:7D:AD:0A", target_node: "proxmox02", template_id: 9102 }
        lb-02:     { vmid: 315, ip: "10.0.3.16", mac: "BC:24:11:C1:3E:0D", target_node: "proxmox03", template_id: 9103 }

    proxmox_nodes:
      hosts:
        proxmox02: { ansible_host: 10.0.1.2 }
        proxmox03: { ansible_host: 10.0.1.3 }
