# --- Proxmox API ---
proxmox_api_host: "YOUR_PROXMOX_HOST:443"
proxmox_user: "YOUR_PROXMOX_USER@pam"
proxmox_token_id: "YOUR_TOKEN_ID"
proxmox_token_secret: "{{ vault_proxmox_token_secret }}"

# --- Infrastructure ---
storage_id: "vm"
bridge: "vmbr0"
vlan_id: "30"

# --- Network Defaults ---
gateway: "10.0.3.254"
dns_servers: "10.0.3.1 10.0.3.2"

# --- Secrets / Passwords ---
# Note: Ensure these are defined in your encrypted vault.yml
lab_password: "{{ vault_lab_password }}"
vault_ansible_password: "{{ vault_ansible_password }}"

# --- Domain Settings ---
domain_name: "YOUR_DOMAIN_NAME.tech"
domain_netbios: "YOUR_NETBIOS"
domain_dn: "DC={{ domain_name.split('.')[0] }},DC={{ domain_name.split('.')[1] }},DC={{ domain_name.split('.')[2] }}"

domain_admin_user: "{{ domain_netbios }}\\Administrator"
domain_admin_password: "{{ vault_lab_password }}"
safe_mode_password: "{{ vault_lab_password }}"
vault_domain_admin_password: "{{ vault_lab_password }}"
ci_user: "administrator"

# Proxmox Root Passwords (For Cloud-Init Injection)
proxmox02_root_password: "{{ vault_proxmox02_root_password }}"
proxmox03_root_password: "{{ vault_proxmox03_root_password }}"
